# HOME WORK 1

In [1]:
import numpy as np

1. Create a one-dimensional array (vector) with the first 10 natural numbers and display its values.

In [2]:
vector = np.arange(1, 11, dtype=int)
print("One-dimensional array with the first 10 natural numbers:")
print(vector)

One-dimensional array with the first 10 natural numbers:
[ 1  2  3  4  5  6  7  8  9 10]


2. Create a two-dimensional array (matrix) with dimensions 3x3, fill it with zeros, and display its values.

In [3]:
zeros_matrix = np.zeros((3,3), dtype=int)
print("Two-dimensional array with dimensions 3x3 filled with zeros:")
print(zeros_matrix)

Two-dimensional array with dimensions 3x3 filled with zeros:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Create a 5x5 array, fill it with random integers in the range from 1 to 10, and display its values.

In [4]:
random_matrix = np.random.randint(1, 11, size=(5, 5))
print("Array with dimensions 5x5 filled with random integers from 1 to 10:")
print(random_matrix)

Array with dimensions 5x5 filled with random integers from 1 to 10:
[[ 4  7  3  3  1]
 [ 8 10  8  5 10]
 [ 7  7  5 10  1]
 [ 8  7  8  1  3]
 [ 2  3  9  7  2]]


4. Create a 4x4 array, fill it with random real numbers in the range from 0 to 1, and display its values.



In [5]:
random_matrix_f = np.random.random((4, 4))
print("Array with dimensions 4x4 filled with random real numbers from 0 to 1:")
print(random_matrix_f)

Array with dimensions 4x4 filled with random real numbers from 0 to 1:
[[0.85158755 0.14819868 0.1531164  0.11720648]
 [0.36953871 0.92123919 0.76367049 0.63543607]
 [0.93122167 0.03201622 0.32296558 0.13729301]
 [0.45134213 0.41937486 0.19793416 0.82906067]]


5. Create two one-dimensional arrays with a size of 5, fill them with random integers in the range from 1 to 10, and perform element-wise addition, subtraction, and multiplication on them.

In [6]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
print(f"Addition result: {a + b}")
print(f"Subtraction result: {a - b}")
print(f"Multiplication result: {a * b}")

Addition result: [17  9  3  8  5]
Subtraction result: [-1  3 -1  4  1]
Multiplication result: [72 18  2 12  6]


6. Create two vectors with a size of 7, fill them with arbitrary numbers, and find their scalar product.

In [7]:
a = np.random.randint(1, 31, size=7)
b = np.random.randint(1, 31, size=7)
print(f"Scalar product: {np.dot(a,b)}")

Scalar product: 1395


7. Create two matrices with dimensions 2x2 and 2x3, fill them with random integers in the range from 1 to 10, and multiply them together.

In [8]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
print("Multiplication result:")
print(np.dot(a,b))

Multiplication result:
[[23 91 33]
 [35 83 33]]


8. Create a 3x3 matrix, fill it with random integers in the range from 1 to 10, and find its inverse matrix.

In [9]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Inverse matrix:")
print(np.linalg.inv(matrix))

Inverse matrix:
[[-0.23076923 -0.30769231  0.46153846]
 [ 0.40659341  0.20879121 -0.38461538]
 [-0.14285714  0.14285714 -0.        ]]


9. Create a 4x4 matrix, fill it with random real numbers in the range from 0 to 1, and transpose it.

In [10]:
matrix = np.random.rand(4, 4)
print("Transposed matrix:")
print(matrix.T)

Transposed matrix:
[[0.29911147 0.010933   0.99518597 0.0331601 ]
 [0.6384035  0.57885548 0.87824506 0.12519083]
 [0.44246274 0.49854219 0.96745936 0.40551633]
 [0.06280074 0.11170357 0.76639779 0.59404452]]


10. Create a 3x4 matrix and a vector with a size of 4, fill them with random integers in the range from 1 to 10, and perform matrix-vector multiplication.

In [11]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)
print("Matrix-vector multiplication result:")
print(np.dot(matrix, vector))

Matrix-vector multiplication result:
[115 127  95]


11. Create a 2x3 matrix and a vector with a size of 3, fill them with random real numbers in the range from 0 to 1, and perform matrix-vector multiplication.

In [12]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
print("Result of matrix-vector multiplication:")
print(np.dot(matrix, vector))

Result of matrix-vector multiplication:
[0.59684901 0.25732792]


12. Create two matrices with dimensions 2x2, fill them with random integers in the range from 1 to 10, and perform element-wise multiplication.

In [13]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
print("Result of element-wise multiplication:")
print(matrix1 * matrix2)

Result of element-wise multiplication:
[[56  4]
 [10 42]]


13. Create two matrices with dimensions 2x2, fill them with random integers in the range from 1 to 10, and find their product.

In [14]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
print("Multiplication result:")
print(np.dot(matrix1, matrix2))

Multiplication result:
[[28 19]
 [32 22]]


14. Create a 5x5 matrix, fill it with random integers in the range from 1 to 100, and find the sum of its elements.

In [15]:
matrix = np.random.randint(1, 101, size=(5, 5))
print(f"The sum of matrix elements: {matrix.sum()}")

The sum of matrix elements: 1244


15. Create two 4x4 matrices, fill them with random integers in the range from 1 to 10, and find their difference.

In [16]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Difference result:")
print(matrix1 - matrix2)

Difference result:
[[-3  4  4  2]
 [-2  8  5  3]
 [ 3 -3  3 -1]
 [ 0  0 -4 -9]]


16. Create a 3x3 matrix, fill it with random real numbers in the range from 0 to 1, and find a column vector that contains the sum of elements of each row of the matrix.

In [17]:
matrix = np.random.rand(3, 3)
matrix_sum = np.sum(matrix, axis=1)
print("Column vector with the sums of row elements:")
print(matrix_sum.reshape(-1, 1))

Column vector with the sums of row elements:
[[2.10610951]
 [2.13834271]
 [1.4496627 ]]


17. Create a 3x4 matrix with arbitrary integers and create a matrix with the squares of these numbers.

In [18]:
matrix = np.random.randint(1, 11, size=(3, 4))
print("Matrix with the squares of numbers:")
print(np.square(matrix))

Matrix with the squares of numbers:
[[25  4  9 81]
 [ 1 25  4 64]
 [ 4 16 64 36]]


18. Create a vector with a size of 4, fill it with random integers in the range from 1 to 50, and find a vector with the square roots of these numbers.

In [19]:
vector = np.random.randint(1, 51, size=4)
print("Vector with the square roots:")
print(np.sqrt(vector))

Vector with the square roots:
[2.23606798 2.23606798 6.55743852 5.74456265]
